name: Android CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build APK
      run: ./gradlew assembleRelease  # Build the release version of my app

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk

    - name: Deploy to Google Play (optional)
      if: github.ref == 'refs/heads/main'  # Only deploy if the push is to the main branch
      uses: r0adkll/upload-google-play@v1.0.3
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}  #  Google Play service account JSON
        packageName: com.yourapp.package
        releaseFiles: app/build/outputs/apk/release/app-release.apk
